version: "3.5"
services:
    django:
        build: .
        image: ppoile/athletica-adapter:0.6
        container_name: athletica-adapter
        stdin_open: true
        tty: true
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
        restart: always
networks:
    default:
        external: true
        name: docker-athletica_default
